{% set name = "opennb" %}
{% set version = "0.2.3" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f9e20f9872ce7d7ba47e4a22d9bb1a639007c6b43a9ee8c5bcb901c7e7b62ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - opennb = opennb:main

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - notebook

test:
  imports:
    - opennb
  commands:
    - pip check
    - opennb --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Open Jupyter notebooks from GitHub repositories or URLs directly in Jupyter.
  license: MIT
  home: https://github.com/basnijholt/opennb
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
